version: "3.9"
services:
  palworld:
    build: .
    ports:
      - "8211:8211/udp"
    restart: always
    volumes:
      - ./Saved:/home/steam/Steam/steamapps/common/PalServer/Pal/Saved
    user: "1000:1000"